### ISSUE TITLE
Blobporter keeps uploading when previous blocks are detected and can't be deleted.

### ISSUE THREAD

**Issue by ewold** [Azure/blobporter#66] opened 2017-11-24 08:45 UTC
File Size: 1.2GBytes

We tried the upload before but the container went OOM at a sudden point which caused the blob to have uncommitted blocks. 

```
INFO: Uploading file
BlobPorter
Copyright (c) Microsoft Corporation.
Version: 0.5.10
---------------
Files to Transfer (file-blockblob) :
 Source: /nv/file.mp4 Size:1206999808
Warning! uncommitted blocks detected for blob file.mp4
Attempting to clean them up
Can't delete uncommitted blocks for the blob: file.mp4. A committed blob with the same name already exists
```

After this message, the stats show that parts are being uploaded and comes in a loop where we killed the process after it has uploaded already 30GB of data. Also on our azure account side, it's clear that the blob storage is much bigger than should. 
It can be this is more a problem in the storage go sdk.

**Comment by giventocode** [comment] 2017-11-26 18:25
More information will be helpful to find out what happened here.  Can you clarify: "After this message, the stats show that parts are being uploaded and comes in a loop where we killed the process after it has uploaded already 30GB of data."  Specifically, what stats you are referring to and what you mean with "comes in a loop"?

**Comment by ewold** [comment] 2017-11-27 14:44
We are running blobporter in a docker container. The message displayed above is shown, blobporter keeps running, no exit.  The stats come from the docker stats command which gives a overall view about the total netwerk I/O in and out. For the 1.2GB file we had a receive of 1.3GB , outgoing I/O kept going up until we killed the container which at that moment had transferred 30GB of network I/O. 
If we look at graphs of our azure blob storage we have a storage much bigger than total of the source. 
This only happens with blobs that have uncommitted blocks that couldn't be delete with the zero byte block.

**Comment by giventocode** [comment] 2017-11-27 16:43
Thanks for the additional information.

>We are running blobporter in a docker container. The message displayed above is shown, blobporter keeps running, no exit. 

This is the as designed behavior. The rationale here is that once the transfer succeeds the newest uncommitted blocks will be committed and the old ones will be asynchronously garbage collected. If blobporter exits in this scenario, the user would have to rename or delete the existing blob and upload an empty blob with the old name to "clean up" the uncommitted blocks, and then try the transfer again.
 
More information about how uncommitted blocks are handled, including retention periods, check the Remarks section of the following link:

https://docs.microsoft.com/en-us/rest/api/storageservices/put-block

Hope this clarifies the behavior, otherwise let me know.

**Comment by ewold** [comment] 2017-11-27 17:01
Thanks for clarifying. Is there a way we can intercept this or an option to fail the transfer if a zero byte overwrite before uploading has failed. Now blobporter just keeps uploading without quitting which is hard to detect and costs us a lot of waisted bandwidth.

**Comment by giventocode** [comment] 2017-11-27 18:18
Perhaps I am missing something, but what is the point of the failing the transfer when uncommitted blocks are detected? Please note this only occurs if a previous transfer failed, in which case blobporter exits with an error. Blobporter won't transfer more data that is needed, however, it will retry requests that fail due to a transient failure (e.g. throttling). If you want to minimize the max bandwidth you can decrease the number of workers (-g ) to low digit number, this will reduce the memory utilization as well.

**Comment by giventocode** [comment] 2017-11-29 00:37
Closing this one as it seems like the as designed behavior is happening here. When resumeable transfers are implemented this issue will be moot.

**Closed by giventocode** 2017-11-29 00:37 UTC
